### ISSUE TITLE
FEATURE: force results to be in unit

### ISSUE THREAD

**Issue by Kapsonfire-DE** [evanwashere/mitata#10]
Please add a parameter to set up a unit like us/ms to the run command, so all results will be in the given unit.

**Comment by evanwashere** [comment]
mitata has been designed from early on to have a fixed column width in order to show compact benchmark results immediately in the terminal. Locking the unit would make it overflow or show `0.0000` and break the layout. However, you can get precise nanoseconds representation by using the `run()` function return value.
