### ISSUE TITLE
Feature: allow specifying timeout

### ISSUE THREAD

**Issue by smeijer** [evanwashere/mitata#14]
Currently, benches can run forever. Having a timeout option would be nice.

**Comment by evanwashere** [comment]
It's quite a messy problem to solve, and even harder if you are running on bare-bones runtime

There are two types of timeouts:
- cpu time
- wall clock time

wall clock time one is much easier to achieve, as it only requires `setTimeout` and event loop to not be blocked. meanwhile cpu time timeout is much harder to achieve because it requires a separate watcher thread/worker/process to be spawned that can terminate the main (halted) one

a robust timeout feature would have to implement both types and require making whole benchmarking process aware of timeouts being forced (on-disk/cross-thread/process state & additional tracking overhead during benchmarking)

one thing for sure is that core of mitata will never have such functionality but maybe one day there will be bigger brother library or additional function/module that has this
